version: 2.1

orbs:
  maven: circleci/maven@1.3.0
jobs:
   build:
   steps:
      - checkout
      - run  
          name: Download Selenium
		command: curl -O http://selenium-release.storage.googleapis.com/4.0/selenium-server-standalone-4.0.0-alpha-2.jar
      - run
          name: Start Selenium
	  command: java -jar selenium-server-standalone-4.0.0-alpha-2.jar
          background: true
workflows:
  maven_test:
    jobs:	
      - maven/test:
          command: '-Dtest=RunnerClass test'
      # - mvn -Dtest=RunnerClass test # checkout, build, test, and upload test results
